@startuml

interface Strategy{
operate()
}

class StrategyRead{
}
class StrategySport{
}
class StrategyStudy{
}

class StrategyContext{
    Strategy stretegy
    operate()
}

Strategy <|-- StrategyRead
Strategy <|-- StrategySport
Strategy <|-- StrategyStudy

@enduml